name: ci workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: export -p
      run:  export -p

    - name: brew install gnu-sed
      if:   matrix.os == 'macos-11.0'
      run:  brew install gnu-sed

    - name: brew install 
      run:  brew install automake autoconf libtool pkg-config make cmake meson gperf itstool tree lzip nasm doxygen protobuf xmlto

    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg
        mv ndk-pkg $(brew --prefix)/bin

    - name: ndk-pkg version
      run:  ndk-pkg version

    - uses: actions/checkout@v2

    - name: mv *.sh ~/.ndk-pkg/formula
      run: |
        install -d $HOME/.ndk-pkg/formula
        mv *.sh    $HOME/.ndk-pkg/formula

    - name: ndk-pkg install boost
      run:  ndk-pkg install boost
