name: workflow17

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        pkg: [silicon,sl,soundtouch,spdlog,starship,stylua,supervisord,suricata,swig,syncthing,szip,taglib,tbox,tcc,tcl-core,tcpdump,tdu,tealdeer,tectonic,tengo]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: export -p

      - name: install ndk-pkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/bin/ndk-pkg
          chmod u+x ndk-pkg
          mv ndk-pkg $(brew --prefix)/bin

      - run: ndk-pkg env

      - uses: actions/checkout@v2

      - run: install -d ~/.ndk-pkg/repos.d/offical
      - run: mv *       ~/.ndk-pkg/repos.d/offical

      - run: ndk-pkg install ${{ matrix.pkg }}
