name: workflow2

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11]
        os: [ubuntu-22.04]
        pkg: [fdroidcl,fff,figlet,findutils,fish,flatbuffers,flex,fortune,fselect,fsmon,fzf,fzy,gawk,gbt,gd,gdbm,gdu,geographiclib,germanium,geth,gh,git-lfs,glog,glow,glslang,gmake,gnu-barcode,gnu-coreutils,gnu-which,gnupg,gnutls,godu,gogs,gomobile,google-benchmark,goreleaser,gosh,gotop,gotty,gox,gpatch,gperf,gping,gpsim,gputils,grep,grex,gron,grpc,gsed,gtar,gzip,helm,help2man,hexdump,hexyl,htop,htslib,hugo,hunspell,hwloc,hydroxide,hyperfine,id3lib,ideviceinstaller,imagemagick,ixwebsocket,jfrog-cli,jpeg,jq]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: export -p

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg setup
      - run: ./ndk-pkg env
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg ndkinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core
      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            timestamp-created: 1673675503
            timestamp-updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: ./ndk-pkg install ${{ matrix.pkg }}
