name: workflow2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15]
        pkg: [double-conversion,duf,dust,esbuild,faac,faad2,fd,fdk-aac,ffmpeg,findutils,fish,flex,fzf,gawk,gdbm,gh,glog,gnu-coreutils,gnu-sed,gnu-which,gnupg,gnutls,gogs,gomobile,google-benchmark,gperf,gping,graphite2,grep,grpc]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run: export -p

    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg
        mv ndk-pkg $(brew --prefix)/bin

    - run: ndk-pkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.ndk-pkg/repos.d/offical
    - run: mv *       ~/.ndk-pkg/repos.d/offical

    - run: ndk-pkg install ${{ matrix.pkg }}
