name: workflow2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15]
        pkg: [libarchive,libass,libatomic_ops,libb2,libbcrypt,libbthread,libcaca,libcap,libcddb,libcdio,libcroco,libexecinfo,libexif,libgit2,libimagequant,libirecovery,libisoburn,libmetalink,libnl,libpipeline,libpsl,libsamplerate,libsigsegv,libsmi,libtirpc,libtool,libxslt,links,lodepng,lynx,lzip,make,mbedtls,mesalink,mpg123,mpir,nasm,nginx,ngtcp2,ntbtls,numactl,openlibm,openmpi,openssl-fips,packcc,pango,patch,pixman,pkg-config,pkgconf]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run: export -p

    - run: brew install gnu-sed
      if:  matrix.os == 'macos-11.0'

    - run: brew install automake autoconf libtool pkg-config make cmake meson gperf itstool tree lzip nasm help2man doxygen protobuf xmlto ghostscript
 
    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg
        mv ndk-pkg $(brew --prefix)/bin

    - run: ndk-pkg version

    - uses: actions/checkout@v2

    - name: mv *.sh ~/.ndk-pkg/formula
      run: |
        install -d $HOME/.ndk-pkg/formula
        mv *.sh    $HOME/.ndk-pkg/formula

    - run: ndk-pkg install ${{ matrix.pkg }}
