name: workflow2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        pkg: [cjson,cmake,cppcheck,cpu_features,crosstool-ng,ctop,darkhttpd,dash,delta,diffutils,dog,dos2unix,double-conversion,duf,dust,esbuild,faac,faad2,fd,fdk-aac]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: export -p

      - name: install ndk-pkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
          chmod u+x ndk-pkg
          mv ndk-pkg $(brew --prefix)/bin

      - run: ndk-pkg env

      - uses: actions/checkout@v2

      - run: install -d ~/.ndk-pkg/repos.d/offical
      - run: mv *       ~/.ndk-pkg/repos.d/offical

      - run: |
            if [ -n "$ANDROID_NDK_LATEST_HOME" ] ; then
                export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
            fi
            ndk-pkg install ${{ matrix.pkg }} --tree
