name: workflow4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        pkg: [gpatch,gperf,gping,graphite2,grep,grpc,gsed,gtar,gzip,help2man,hexdump,hiredis,htop,hugo,hunspell,hwloc,hyperfine,id3lib,ideviceinstaller,jbig2dec]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: export -p

      - name: install ndk-pkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
          chmod u+x ndk-pkg
          mv ndk-pkg $(brew --prefix)/bin

      - run: ndk-pkg env

      - uses: actions/checkout@v2

      - run: install -d ~/.ndk-pkg/repos.d/offical
      - run: mv *       ~/.ndk-pkg/repos.d/offical

      - run: |
            brew uninstall go@1.15 || true
            export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
            ndk-pkg install ${{ matrix.pkg }} --tree
