name: workflow5

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11]
        os: [ubuntu-22.04]
        pkg: [open264,openal-soft,openblas,opencolorio,openlibm,openmpi,openssl-fips,p7zip,packcc,patchelf,pcapplusplus,pdfium,perl,pget,physfs,pigz,pjsip,pkg-config,pkgconf,plog,pngquant,poco,procs,progress,proj,proot2,pup,putty,pybind11,qrencode,quiche,quickjs,rang,rapidjson,rav1e,rclone,re2c,restic,rhash,ripgrep,rlwrap,rsass,rsync,rtmpdump,rtorrent,rust-analyzer,sassc,scc,sd,shc,shell2http,shiori,silicon,skia,sl,soundtouch,spdlog,starship,stylua,supervisord,suricata,svn-lite,swig,syncthing,szip,taglib,tbox,tcc,tcl-core,tcpdump,tdu,tealdeer,tectonic,tengo,texinfo]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: export -p

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg setup
      - run: ./ndk-pkg env
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg ndkinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core
      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            timestamp-created: 1673675503
            timestamp-updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: ./ndk-pkg install ${{ matrix.pkg }}
