name: workflow6

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11]
        os: [ubuntu-22.04]
        pkg: [tig,tinyxml2,tmux,tokei,toml++,toml11,tree,ttyd,ttygif,ttyrec,tweego,unbound,universal-ctags,unrar,unzip,usbmuxd,utf8.h,utfcpp,vala,vegeta,vim,virustotal-cli,vsftpd,wabt,wasm3,watchexec,webhook,wget,wolfssl,wuzz,xh,xmake,xorriso,xpup,xvid,yasm,youtubedr,yq,yyjson,zeromq,zlib-ng,zlog,zoxide,zsh,zsync]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: export -p

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg env
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg ndkinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core
      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            timestamp-created: 1673675503
            timestamp-updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: ./ndk-pkg install ${{ matrix.pkg }}
