name: workflow7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15]
        pkg: [universal-ctags,unrar,unzip,usbmuxd,vala,vsftpd,wabt,wasm3,webhook,wget,wolfssl,xorriso,xvid,yasm,youtubedr,yq,zola,zsh,zsync,hexdump]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run: export -p

    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg
        mv ndk-pkg $(brew --prefix)/bin

    - run: ndk-pkg --version

    - uses: actions/checkout@v2

    - run: install -d ~/.ndk-pkg/repos.d/offical
    - run: mv *       ~/.ndk-pkg/repos.d/offical

    - run: ndk-pkg install ${{ matrix.pkg }}
