name: workflow8

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11]
        os:  [ubuntu-22.04]
        abi: [armeabi-v7a, arm64-v8a]
        pkg: [luajit,luau,lychee,lynx,lzip,lzop,magic_enum,mcfly,md4c,mdbook,mediainfo,mesalink,mimalloc,miniz,minizip-ng,mm-wiki,mold,mosh,mozjpeg,mpdecimal,mpg123,mpir,mruby,msgpack-c,nano,nanomsg,nasm,navi,ncdu,neofetch,netpbm,nginx,ngtcp2,ninja,nng,nnn,ntbtls,numactl]

    runs-on: ${{ matrix.os }}

    steps:
      - run: export -p

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg env
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg ndkinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core
      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            timestamp-created: 1673675503
            timestamp-updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: |
          MIN_SDK_API_LEVEL=$(./ndk-pkg info ${{ matrix.pkg }} sdk.api)
          if [ -z "$MIN_SDK_API_LEVEL" ] ; then
            MIN_SDK_API_LEVEL=21
          fi
          ./ndk-pkg install android-$MIN_SDK_API_LEVEL/${{ matrix.abi }}/${{ matrix.pkg }}
